# Local Raspberry Pi lab setup

- hosts: rpis
  become: yes
  tasks:
    - import_tasks: common_install_tasks.yml
    - import_tasks: docker_install_tasks.yml

    - name: Add 'pi' user to 'docker' group
      user:
        name: pi
        append: yes
        groups: docker

- hosts: pi400
  become: yes
  tasks:
    - name: Get python version
      shell: python --version
      register: x_python_version

    - name: Debug python version
      debug:
        var: x_python_version
        verbosity: 2
